# Generated by Django 5.2.4 on 2025-08-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(choices=[('Automobile Accident', 'Automobile Accident'), ('Medical Negligence', 'Medical Negligence'), ('Slip & Fall', 'Slip & Fall'), ('Other Injury or Accident', 'Other Injury or Accident')], max_length=50)),
                ('accident_time', models.CharField(max_length=50)),
                ('fault', models.CharField(choices=[('No, I was not at fault', 'No, I was not at fault'), ('Partially at fault', 'Partially at fault'), ('Not sure', 'Not sure')], max_length=50)),
                ('medical', models.TextField(help_text='Comma-separated list of medical options')),
                ('attorney', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
