# Generated by Django 5.2.4 on 2025-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='accident_time',
            field=models.CharField(choices=[('Within 1-3 months', 'Within 1-3 months'), ('Within 3-6 months', 'Within 3-6 months'), ('Within 9-12 Months', 'Within 9-12 Months'), ('Within 24 Months', 'Within 24 Months')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='medical',
            field=models.TextField(help_text='Comma-separated list of selected medical attention options'),
        ),
    ]
