# Generated by Django 5.2.4 on 2025-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_accident_time_alter_lead_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='accident_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='attorney',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fault',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='injury_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='medical',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
