# Generated by Django 5.2.4 on 2025-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_accident_time_alter_lead_attorney_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tf_cert_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
