# Generated by Django 5.2.5 on 2025-08-14 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_tf_cert_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='accident_time',
            field=models.CharField(choices=[('Within 1-3 months', 'Within 1-3 months'), ('Within 3-6 months', 'Within 3-6 months'), ('Within 9-12 Months', 'Within 9-12 Months'), ('Within 24 Months', 'Within 24 Months')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='attorney',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fault',
            field=models.CharField(choices=[('No, I was not at fault', 'No, I was not at fault'), ('Partially at fault', 'Partially at fault'), ('Not sure', 'Not sure')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='injury_type',
            field=models.CharField(choices=[('Automobile Accident', 'Automobile Accident'), ('Medical Negligence', 'Medical Negligence'), ('Slip & Fall', 'Slip & Fall'), ('Other Injury or Accident', 'Other Injury or Accident')], max_length=100),
        ),
    ]
